AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.2

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
